### ISSUE TITLE
"You're not authorized" on front page

### ISSUE THREAD

**Issue by NicolaiVBonderup** [gode-ting/hackerNews-clone-project-frontend#3]
When navigating to the front page, nothing is displayed in the body but a large error prompt, telling me that I am not authorized.

![da2f8b5d42a56187238ded52856d70f5](https://user-images.githubusercontent.com/8896639/32782118-9ac1a1da-c947-11e7-9136-0d98df0d5632.png)

**Comment by hilleer** [comment]
See #5
