### ISSUE TITLE
Error page when navigating to "Login" or "Comments"

### ISSUE THREAD

**Issue by NicolaiVBonderup** [gode-ting/hackerNews-clone-project-frontend#4]
If attempting to navigate to the Login or Comments pages from the frontpage, a default error page is displayed instead.
![b3f638a9e49953511ff64e73b66e73b1](https://user-images.githubusercontent.com/8896639/32782168-caeff910-c947-11e7-9415-32cd9bb29ebc.png)

**Comment by hilleer** [comment]
See #5
