### ISSUE TITLE
"Submit" button error

### ISSUE THREAD

**Issue by NicolaiVBonderup** [gode-ting/hackerNews-clone-project-frontend#5]
When pressing the "Submit" button on the frontpage, the browser instead downloads an extensionless, contentless file named "submit".

**Comment by hilleer** [comment]
Hi Nicolai,

Thanks for reporting the issue.

After reading all the issues you made, I believe you ended up at a wrong url somehow. What url did you access our frontend at, and where did you find it? 

The correct url is: http://hacker-newz.bitballoon.com/

**Comment by NicolaiVBonderup** [comment]
Thanks for the response,

I used the URL that's posted on the Collabedit page where we posted our URLs, http://collabedit.com/kr634 in particular. I'll use this other URL from now on.

**Comment by hilleer** [comment]
Aha, ofc. I added it there now :-) Thanks!
